services:
  postgres:
    image: ankane/pgvector:latest # Back to proven image
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=yourdb
    command: postgres -c shared_preload_libraries=vector

  app:
    image: aagi
    container_name: agents
    environment:
      - POSTGRES_URL=postgresql://postgres:yourpassword@postgres:5432/yourdb
      # Give more time for DB init
      - DB_CONNECT_TIMEOUT=30
    depends_on:
      - postgres

volumes:
  postgres_data:
