version: '3.8'

services:
  app:
    image: aagid
    network_mode: "host" # This replaces the ports mapping and extra_hosts
    tty: true # Equivalent to -t in docker run
    stdin_open: true # Equivalent to -i in docker run
