services:
  app:
    image: aagi
    container_name: agents
    environment:
      - NODE_ENV=production
      - POSTGRES_URL=postgresql://postgres:yourpassword@postgres:5432/yourdb
    networks:
      - proxy
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=yourdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - proxy

networks:
  proxy:
    external: true
    name: docker_proxy

volumes:
  postgres_data:
